# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nameselection.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(466, 360)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("fluent_gui/title_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 421, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.inlet_number = QtWidgets.QSpinBox(self.layoutWidget)
        self.inlet_number.setMinimum(1)
        self.inlet_number.setObjectName("inlet_number")
        self.horizontalLayout_2.addWidget(self.inlet_number)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.outlet_number = QtWidgets.QSpinBox(self.layoutWidget)
        self.outlet_number.setMinimum(1)
        self.outlet_number.setObjectName("outlet_number")
        self.horizontalLayout_2.addWidget(self.outlet_number)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.distrib_number = QtWidgets.QSpinBox(self.layoutWidget)
        self.distrib_number.setProperty("value", 1)
        self.distrib_number.setObjectName("distrib_number")
        self.horizontalLayout_2.addWidget(self.distrib_number)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.part_tree = QtWidgets.QTreeWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.part_tree.sizePolicy().hasHeightForWidth())
        self.part_tree.setSizePolicy(sizePolicy)
        self.part_tree.setMinimumSize(QtCore.QSize(220, 0))
        self.part_tree.setObjectName("part_tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        self.horizontalLayout.addWidget(self.part_tree)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.quick_distribfh_btn = QtWidgets.QRadioButton(self.groupBox)
        self.quick_distribfh_btn.setObjectName("quick_distribfh_btn")
        self.verticalLayout_3.addWidget(self.quick_distribfh_btn)
        self.quick_distribfc_btn = QtWidgets.QRadioButton(self.groupBox)
        self.quick_distribfc_btn.setObjectName("quick_distribfc_btn")
        self.verticalLayout_3.addWidget(self.quick_distribfc_btn)
        self.verticalLayout.addWidget(self.groupBox)
        self.finish_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.finish_btn.setObjectName("finish_btn")
        self.verticalLayout.addWidget(self.finish_btn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label.setBuddy(self.inlet_number)
        self.label_2.setBuddy(self.outlet_number)
        self.label_3.setBuddy(self.distrib_number)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "命名模板"))
        self.label.setText(_translate("Form", "进口数量"))
        self.label_2.setText(_translate("Form", "出口数量"))
        self.label_3.setText(_translate("Form", "分配箱数量"))
        self.part_tree.headerItem().setText(0, _translate("Form", "模型部件"))
        __sortingEnabled = self.part_tree.isSortingEnabled()
        self.part_tree.setSortingEnabled(False)
        self.part_tree.topLevelItem(0).setText(0, _translate("Form", "进口半球（inlet_sphere)"))
        self.part_tree.topLevelItem(1).setText(0, _translate("Form", "进口(ai)"))
        self.part_tree.topLevelItem(2).setText(0, _translate("Form", "过滤芯(filter)"))
        self.part_tree.topLevelItem(3).setText(0, _translate("Form", "导流段(cone)"))
        self.part_tree.topLevelItem(4).setText(0, _translate("Form", "蜗壳(volute)"))
        self.part_tree.topLevelItem(5).setText(0, _translate("Form", "叶轮(fan)"))
        self.part_tree.topLevelItem(6).setText(0, _translate("Form", "扩张段(diffuser)"))
        self.part_tree.topLevelItem(7).setText(0, _translate("Form", "蒸发器(evap)"))
        self.part_tree.topLevelItem(8).setText(0, _translate("Form", "分配箱(distrib)"))
        self.part_tree.topLevelItem(9).setText(0, _translate("Form", "加热芯(heater)"))
        self.part_tree.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("Form", "快速模板"))
        self.quick_distribfh_btn.setText(_translate("Form", "全热分配箱"))
        self.quick_distribfc_btn.setText(_translate("Form", "全冷分配箱"))
        self.finish_btn.setText(_translate("Form", "导入模板"))
