# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from HorizontalBar import HorizontalTabBar


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(472, 490)
        MainWindow.setMaximumSize(QtCore.QSize(1500, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../.designer/backup/fluent_gui/title_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStatusTip("")
        MainWindow.setStyleSheet("QToorBar::handle{height:40px; spacing: 10px;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 521, 471))
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 450))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStatusTip("")
        self.tabWidget.setWhatsThis("")
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("QTabBar::tab {height:55px; min-width: 80px;boder:none}\n"
"QTabWidget::tab-bar { alignment: left; }")
        self.tabWidget.setTabBar(HorizontalTabBar())
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.RPM_tab = QtWidgets.QWidget()
        self.RPM_tab.setAccessibleDescription("")
        self.RPM_tab.setObjectName("RPM_tab")
        self.frame = QtWidgets.QFrame(self.RPM_tab)
        self.frame.setGeometry(QtCore.QRect(30, 60, 291, 341))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(30, 10, 40, 20)
        self.gridLayout_2.setHorizontalSpacing(30)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.hil_spinbox = QtWidgets.QSpinBox(self.frame)
        self.hil_spinbox.setEnabled(False)
        self.hil_spinbox.setMaximum(5000)
        self.hil_spinbox.setSingleStep(50)
        self.hil_spinbox.setProperty("value", 3000)
        self.hil_spinbox.setObjectName("hil_spinbox")
        self.gridLayout_2.addWidget(self.hil_spinbox, 7, 1, 1, 1)
        self.trl_spinbox = QtWidgets.QSpinBox(self.frame)
        self.trl_spinbox.setEnabled(False)
        self.trl_spinbox.setMaximum(5000)
        self.trl_spinbox.setSingleStep(50)
        self.trl_spinbox.setProperty("value", 3000)
        self.trl_spinbox.setObjectName("trl_spinbox")
        self.gridLayout_2.addWidget(self.trl_spinbox, 6, 1, 1, 1)
        self.hil_label = QtWidgets.QLabel(self.frame)
        self.hil_label.setEnabled(False)
        self.hil_label.setObjectName("hil_label")
        self.gridLayout_2.addWidget(self.hil_label, 7, 0, 1, 1)
        self.bil_spinbox = QtWidgets.QSpinBox(self.frame)
        self.bil_spinbox.setEnabled(False)
        self.bil_spinbox.setMaximum(5000)
        self.bil_spinbox.setSingleStep(50)
        self.bil_spinbox.setProperty("value", 3000)
        self.bil_spinbox.setObjectName("bil_spinbox")
        self.gridLayout_2.addWidget(self.bil_spinbox, 3, 1, 1, 1)
        self.vent_spinbox = QtWidgets.QSpinBox(self.frame)
        self.vent_spinbox.setMaximum(5000)
        self.vent_spinbox.setSingleStep(50)
        self.vent_spinbox.setProperty("value", 3000)
        self.vent_spinbox.setObjectName("vent_spinbox")
        self.gridLayout_2.addWidget(self.vent_spinbox, 0, 1, 1, 1)
        self.defrost_label = QtWidgets.QLabel(self.frame)
        self.defrost_label.setEnabled(False)
        self.defrost_label.setObjectName("defrost_label")
        self.gridLayout_2.addWidget(self.defrost_label, 4, 0, 1, 1)
        self.foot_label = QtWidgets.QLabel(self.frame)
        self.foot_label.setEnabled(False)
        self.foot_label.setObjectName("foot_label")
        self.gridLayout_2.addWidget(self.foot_label, 2, 0, 1, 1)
        self.vent_label = QtWidgets.QLabel(self.frame)
        self.vent_label.setObjectName("vent_label")
        self.gridLayout_2.addWidget(self.vent_label, 0, 0, 1, 1)
        self.trl_label = QtWidgets.QLabel(self.frame)
        self.trl_label.setEnabled(False)
        self.trl_label.setObjectName("trl_label")
        self.gridLayout_2.addWidget(self.trl_label, 6, 0, 1, 1)
        self.defog_label = QtWidgets.QLabel(self.frame)
        self.defog_label.setEnabled(False)
        self.defog_label.setObjectName("defog_label")
        self.gridLayout_2.addWidget(self.defog_label, 5, 0, 1, 1)
        self.foot_spinbox = QtWidgets.QSpinBox(self.frame)
        self.foot_spinbox.setEnabled(False)
        self.foot_spinbox.setMaximum(5000)
        self.foot_spinbox.setSingleStep(50)
        self.foot_spinbox.setProperty("value", 3000)
        self.foot_spinbox.setObjectName("foot_spinbox")
        self.gridLayout_2.addWidget(self.foot_spinbox, 2, 1, 1, 1)
        self.defrost_spinbox = QtWidgets.QSpinBox(self.frame)
        self.defrost_spinbox.setEnabled(False)
        self.defrost_spinbox.setMaximum(5000)
        self.defrost_spinbox.setSingleStep(50)
        self.defrost_spinbox.setProperty("value", 3000)
        self.defrost_spinbox.setObjectName("defrost_spinbox")
        self.gridLayout_2.addWidget(self.defrost_spinbox, 4, 1, 1, 1)
        self.bil_label = QtWidgets.QLabel(self.frame)
        self.bil_label.setEnabled(False)
        self.bil_label.setObjectName("bil_label")
        self.gridLayout_2.addWidget(self.bil_label, 3, 0, 1, 1)
        self.defog_spinbox = QtWidgets.QSpinBox(self.frame)
        self.defog_spinbox.setEnabled(False)
        self.defog_spinbox.setMaximum(5000)
        self.defog_spinbox.setSingleStep(50)
        self.defog_spinbox.setProperty("value", 3000)
        self.defog_spinbox.setObjectName("defog_spinbox")
        self.gridLayout_2.addWidget(self.defog_spinbox, 5, 1, 1, 1)
        self.mode_slider = QtWidgets.QSlider(self.RPM_tab)
        self.mode_slider.setGeometry(QtCore.QRect(320, 90, 31, 271))
        self.mode_slider.setMinimum(1)
        self.mode_slider.setMaximum(7)
        self.mode_slider.setSingleStep(1)
        self.mode_slider.setPageStep(1)
        self.mode_slider.setProperty("value", 1)
        self.mode_slider.setSliderPosition(1)
        self.mode_slider.setOrientation(QtCore.Qt.Vertical)
        self.mode_slider.setInvertedAppearance(True)
        self.mode_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.mode_slider.setTickInterval(1)
        self.mode_slider.setObjectName("mode_slider")
        self.label = QtWidgets.QLabel(self.RPM_tab)
        self.label.setGeometry(QtCore.QRect(20, 30, 381, 20))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.RPM_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 280, 20))
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(40, 50, 281, 211))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setHorizontalSpacing(30)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.evap_label = QtWidgets.QLabel(self.frame_2)
        self.evap_label.setObjectName("evap_label")
        self.gridLayout.addWidget(self.evap_label, 0, 0, 1, 1)
        self.evap_combox = QtWidgets.QComboBox(self.frame_2)
        self.evap_combox.setObjectName("evap_combox")
        self.evap_combox.addItem("")
        self.evap_combox.addItem("")
        self.gridLayout.addWidget(self.evap_combox, 0, 1, 1, 1)
        self.hc_label = QtWidgets.QLabel(self.frame_2)
        self.hc_label.setObjectName("hc_label")
        self.gridLayout.addWidget(self.hc_label, 1, 0, 1, 1)
        self.hc_combox = QtWidgets.QComboBox(self.frame_2)
        self.hc_combox.setObjectName("hc_combox")
        self.hc_combox.addItem("")
        self.hc_combox.addItem("")
        self.gridLayout.addWidget(self.hc_combox, 1, 1, 1, 1)
        self.filter_label = QtWidgets.QLabel(self.frame_2)
        self.filter_label.setObjectName("filter_label")
        self.gridLayout.addWidget(self.filter_label, 2, 0, 1, 1)
        self.filter_combox = QtWidgets.QComboBox(self.frame_2)
        self.filter_combox.setObjectName("filter_combox")
        self.filter_combox.addItem("")
        self.filter_combox.addItem("")
        self.gridLayout.addWidget(self.filter_combox, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.temp_c_2 = QtWidgets.QGroupBox(self.tab_4)
        self.temp_c_2.setGeometry(QtCore.QRect(50, 60, 261, 61))
        self.temp_c_2.setObjectName("temp_c_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.temp_c_2)
        self.horizontalLayout_4.setContentsMargins(40, 10, 40, 10)
        self.horizontalLayout_4.setSpacing(40)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.temp_c_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 381, 20))
        self.label_7.setObjectName("label_7")
        self.valve_table = QtWidgets.QTableWidget(self.tab_3)
        self.valve_table.setGeometry(QtCore.QRect(50, 90, 241, 231))
        self.valve_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.valve_table.setRowCount(1)
        self.valve_table.setObjectName("valve_table")
        self.valve_table.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.valve_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.valve_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.valve_table.setItem(0, 0, item)
        self.valve_table.horizontalHeader().setDefaultSectionSize(100)
        self.valve_table.horizontalHeader().setStretchLastSection(True)
        self.valve_table.verticalHeader().setDefaultSectionSize(40)
        self.valve_slider = QtWidgets.QSlider(self.tab_3)
        self.valve_slider.setGeometry(QtCore.QRect(320, 100, 20, 211))
        self.valve_slider.setMaximum(5)
        self.valve_slider.setPageStep(1)
        self.valve_slider.setProperty("value", 1)
        self.valve_slider.setOrientation(QtCore.Qt.Vertical)
        self.valve_slider.setInvertedAppearance(True)
        self.valve_slider.setInvertedControls(False)
        self.valve_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.valve_slider.setTickInterval(1)
        self.valve_slider.setObjectName("valve_slider")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolBar.setStyleSheet("QToolButton{height:40px;margin-right:10px}\n"
"QToolBar{spacing:10px;}\n"
"\n"
"    ")
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.BottomToolBarArea|QtCore.Qt.RightToolBarArea|QtCore.Qt.TopToolBarArea)
        self.toolBar.setIconSize(QtCore.QSize(45, 35))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionexport = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../fluent_gui/icon/文件导出.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionexport.setIcon(icon1)
        self.actionexport.setObjectName("actionexport")
        self.actionimport = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../fluent_gui/icon/import.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionimport.setIcon(icon2)
        self.actionimport.setObjectName("actionimport")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../fluent_gui/icon/help.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionhelp.setIcon(icon3)
        self.actionhelp.setObjectName("actionhelp")
        self.toolBar.addAction(self.actionhelp)
        self.toolBar.addAction(self.actionexport)
        self.toolBar.addAction(self.actionimport)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.evap_combox.setCurrentIndex(1)
        self.hc_combox.setCurrentIndex(1)
        self.filter_combox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CFD-GUI"))
        self.hil_label.setText(_translate("MainWindow", "Hi-Level"))
        self.defrost_label.setText(_translate("MainWindow", "Defrost"))
        self.foot_label.setText(_translate("MainWindow", "Foot"))
        self.vent_label.setText(_translate("MainWindow", "Vent"))
        self.trl_label.setText(_translate("MainWindow", "Tri-Level"))
        self.defog_label.setText(_translate("MainWindow", "Defog"))
        self.bil_label.setText(_translate("MainWindow", "Bi-Level"))
        self.label.setText(_translate("MainWindow", "*请滑动选择存在的模式，并填入相应转速（RPM）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RPM_tab), _translate("MainWindow", "转速            "))
        self.label_2.setText(_translate("MainWindow", "*请选择拥有的芯体"))
        self.evap_label.setText(_translate("MainWindow", "蒸发器"))
        self.evap_combox.setItemText(0, _translate("MainWindow", "添加"))
        self.evap_combox.setItemText(1, _translate("MainWindow", "无"))
        self.hc_label.setText(_translate("MainWindow", "加热芯"))
        self.hc_combox.setItemText(0, _translate("MainWindow", "添加"))
        self.hc_combox.setItemText(1, _translate("MainWindow", "无"))
        self.filter_label.setText(_translate("MainWindow", "过滤芯"))
        self.filter_combox.setItemText(0, _translate("MainWindow", "添加"))
        self.filter_combox.setItemText(1, _translate("MainWindow", "无"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "芯体参数        "))
        self.temp_c_2.setTitle(_translate("MainWindow", "出口R值"))
        self.pushButton.setText(_translate("MainWindow", "R值填写"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "出口阻值        "))
        self.label_7.setText(_translate("MainWindow", "*请选择温度风门数量，并填入相应的行程"))
        item = self.valve_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "风门名字"))
        item = self.valve_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "风门行程(°)"))
        __sortingEnabled = self.valve_table.isSortingEnabled()
        self.valve_table.setSortingEnabled(False)
        item = self.valve_table.item(0, 0)
        item.setText(_translate("MainWindow", "温度风门1"))
        self.valve_table.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "风门参数        "))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionexport.setText(_translate("MainWindow", "导出模板"))
        self.actionexport.setToolTip(_translate("MainWindow", "导出模板"))
        self.actionexport.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionimport.setText(_translate("MainWindow", "导入模板"))
        self.actionimport.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionhelp.setText(_translate("MainWindow", "帮助"))
