# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'easy_test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(951, 760)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("fluent_gui/title_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 100, 711, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 500))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.requisite_c_area = QtWidgets.QWidget()
        self.requisite_c_area.setGeometry(QtCore.QRect(0, -765, 688, 1154))
        self.requisite_c_area.setMinimumSize(QtCore.QSize(601, 0))
        self.requisite_c_area.setObjectName("requisite_c_area")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.requisite_c_area)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mode_info_frame = QtWidgets.QFrame(self.requisite_c_area)
        self.mode_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mode_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mode_info_frame.setObjectName("mode_info_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mode_info_frame)
        self.gridLayout_3.setContentsMargins(15, 15, 15, 20)
        self.gridLayout_3.setHorizontalSpacing(80)
        self.gridLayout_3.setVerticalSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.finish_mode_info_btn = QtWidgets.QPushButton(self.mode_info_frame)
        self.finish_mode_info_btn.setMinimumSize(QtCore.QSize(120, 35))
        self.finish_mode_info_btn.setObjectName("finish_mode_info_btn")
        self.gridLayout_3.addWidget(self.finish_mode_info_btn, 2, 1, 1, 1)
        self.part_tree = QtWidgets.QTreeWidget(self.mode_info_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.part_tree.sizePolicy().hasHeightForWidth())
        self.part_tree.setSizePolicy(sizePolicy)
        self.part_tree.setMinimumSize(QtCore.QSize(210, 300))
        self.part_tree.setMaximumSize(QtCore.QSize(280, 300))
        self.part_tree.setObjectName("part_tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.part_tree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        self.gridLayout_3.addWidget(self.part_tree, 1, 0, 2, 1)
        self.part_number_hlayout = QtWidgets.QHBoxLayout()
        self.part_number_hlayout.setSpacing(15)
        self.part_number_hlayout.setObjectName("part_number_hlayout")
        self.label_inlet_number = QtWidgets.QLabel(self.mode_info_frame)
        self.label_inlet_number.setObjectName("label_inlet_number")
        self.part_number_hlayout.addWidget(self.label_inlet_number)
        self.inlet_number = QtWidgets.QSpinBox(self.mode_info_frame)
        self.inlet_number.setMinimum(1)
        self.inlet_number.setObjectName("inlet_number")
        self.part_number_hlayout.addWidget(self.inlet_number)
        self.label_outlet_number = QtWidgets.QLabel(self.mode_info_frame)
        self.label_outlet_number.setObjectName("label_outlet_number")
        self.part_number_hlayout.addWidget(self.label_outlet_number)
        self.outlet_number = QtWidgets.QSpinBox(self.mode_info_frame)
        self.outlet_number.setMinimum(1)
        self.outlet_number.setObjectName("outlet_number")
        self.part_number_hlayout.addWidget(self.outlet_number)
        self.label_distrib_number = QtWidgets.QLabel(self.mode_info_frame)
        self.label_distrib_number.setObjectName("label_distrib_number")
        self.part_number_hlayout.addWidget(self.label_distrib_number)
        self.distrib_number = QtWidgets.QSpinBox(self.mode_info_frame)
        self.distrib_number.setProperty("value", 1)
        self.distrib_number.setObjectName("distrib_number")
        self.part_number_hlayout.addWidget(self.distrib_number)
        self.gridLayout_3.addLayout(self.part_number_hlayout, 0, 0, 1, 2)
        self.quick_mode_box = QtWidgets.QGroupBox(self.mode_info_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quick_mode_box.sizePolicy().hasHeightForWidth())
        self.quick_mode_box.setSizePolicy(sizePolicy)
        self.quick_mode_box.setMinimumSize(QtCore.QSize(150, 220))
        self.quick_mode_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.quick_mode_box.setObjectName("quick_mode_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.quick_mode_box)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.energy_checkbox = QtWidgets.QCheckBox(self.quick_mode_box)
        self.energy_checkbox.setObjectName("energy_checkbox")
        self.verticalLayout_4.addWidget(self.energy_checkbox)
        self.quick_distribfc_btn = QtWidgets.QRadioButton(self.quick_mode_box)
        self.quick_distribfc_btn.setChecked(True)
        self.quick_distribfc_btn.setObjectName("quick_distribfc_btn")
        self.verticalLayout_4.addWidget(self.quick_distribfc_btn)
        self.quick_distribfh_btn = QtWidgets.QRadioButton(self.quick_mode_box)
        self.quick_distribfh_btn.setObjectName("quick_distribfh_btn")
        self.verticalLayout_4.addWidget(self.quick_distribfh_btn)
        self.quick_distribbil_btn = QtWidgets.QRadioButton(self.quick_mode_box)
        self.quick_distribbil_btn.setObjectName("quick_distribbil_btn")
        self.verticalLayout_4.addWidget(self.quick_distribbil_btn)
        self.quick_distriblin_btn = QtWidgets.QRadioButton(self.quick_mode_box)
        self.quick_distriblin_btn.setObjectName("quick_distriblin_btn")
        self.verticalLayout_4.addWidget(self.quick_distriblin_btn)
        self.gridLayout_3.addWidget(self.quick_mode_box, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.mode_info_frame)
        self.mass_inlet = QtWidgets.QGroupBox(self.requisite_c_area)
        self.mass_inlet.setMaximumSize(QtCore.QSize(700, 80))
        self.mass_inlet.setObjectName("mass_inlet")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.mass_inlet)
        self.horizontalLayout_4.setContentsMargins(40, 10, 40, 15)
        self.horizontalLayout_4.setSpacing(40)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mass_inlet_label = QtWidgets.QLabel(self.mass_inlet)
        self.mass_inlet_label.setMinimumSize(QtCore.QSize(100, 0))
        self.mass_inlet_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.mass_inlet_label.setObjectName("mass_inlet_label")
        self.horizontalLayout_4.addWidget(self.mass_inlet_label)
        self.mass_inlet_edit = QtWidgets.QLineEdit(self.mass_inlet)
        self.mass_inlet_edit.setMinimumSize(QtCore.QSize(132, 0))
        self.mass_inlet_edit.setMaximumSize(QtCore.QSize(132, 16777215))
        self.mass_inlet_edit.setObjectName("mass_inlet_edit")
        self.horizontalLayout_4.addWidget(self.mass_inlet_edit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.unit_btn = QtWidgets.QPushButton(self.mass_inlet)
        self.unit_btn.setMinimumSize(QtCore.QSize(140, 25))
        self.unit_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.unit_btn.setObjectName("unit_btn")
        self.horizontalLayout_4.addWidget(self.unit_btn)
        self.verticalLayout.addWidget(self.mass_inlet)
        self.evap_c = QtWidgets.QGroupBox(self.requisite_c_area)
        self.evap_c.setMinimumSize(QtCore.QSize(0, 180))
        self.evap_c.setMaximumSize(QtCore.QSize(16777215, 185))
        self.evap_c.setObjectName("evap_c")
        self.gridLayout = QtWidgets.QGridLayout(self.evap_c)
        self.gridLayout.setContentsMargins(40, 10, 40, 10)
        self.gridLayout.setHorizontalSpacing(40)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.evap_c2_edit = QtWidgets.QLineEdit(self.evap_c)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evap_c2_edit.sizePolicy().hasHeightForWidth())
        self.evap_c2_edit.setSizePolicy(sizePolicy)
        self.evap_c2_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.evap_c2_edit.setObjectName("evap_c2_edit")
        self.gridLayout.addWidget(self.evap_c2_edit, 0, 3, 1, 1)
        self.label_evap_x1 = QtWidgets.QLabel(self.evap_c)
        self.label_evap_x1.setMinimumSize(QtCore.QSize(100, 0))
        self.label_evap_x1.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_evap_x1.setObjectName("label_evap_x1")
        self.gridLayout.addWidget(self.label_evap_x1, 1, 0, 1, 1)
        self.label_evap_C2 = QtWidgets.QLabel(self.evap_c)
        self.label_evap_C2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_evap_C2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_evap_C2.setObjectName("label_evap_C2")
        self.gridLayout.addWidget(self.label_evap_C2, 0, 2, 1, 1)
        self.evap_c1_edit = QtWidgets.QLineEdit(self.evap_c)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evap_c1_edit.sizePolicy().hasHeightForWidth())
        self.evap_c1_edit.setSizePolicy(sizePolicy)
        self.evap_c1_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.evap_c1_edit.setObjectName("evap_c1_edit")
        self.gridLayout.addWidget(self.evap_c1_edit, 0, 1, 1, 1)
        self.evap_x2_edit = QtWidgets.QLineEdit(self.evap_c)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evap_x2_edit.sizePolicy().hasHeightForWidth())
        self.evap_x2_edit.setSizePolicy(sizePolicy)
        self.evap_x2_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.evap_x2_edit.setObjectName("evap_x2_edit")
        self.gridLayout.addWidget(self.evap_x2_edit, 1, 3, 1, 1)
        self.label_evap_z1 = QtWidgets.QLabel(self.evap_c)
        self.label_evap_z1.setMinimumSize(QtCore.QSize(100, 0))
        self.label_evap_z1.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_evap_z1.setObjectName("label_evap_z1")
        self.gridLayout.addWidget(self.label_evap_z1, 3, 0, 1, 1)
        self.label_evap_y1 = QtWidgets.QLabel(self.evap_c)
        self.label_evap_y1.setMinimumSize(QtCore.QSize(100, 0))
        self.label_evap_y1.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_evap_y1.setObjectName("label_evap_y1")
        self.gridLayout.addWidget(self.label_evap_y1, 2, 0, 1, 1)
        self.evap_z2_edit = QtWidgets.QLineEdit(self.evap_c)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evap_z2_edit.sizePolicy().hasHeightForWidth())
        self.evap_z2_edit.setSizePolicy(sizePolicy)
        self.evap_z2_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.evap_z2_edit.setObjectName("evap_z2_edit")
        self.gridLayout.addWidget(self.evap_z2_edit, 3, 3, 1, 1)
        self.label_evap_z2 = QtWidgets.QLabel(self.evap_c)
        self.label_evap_z2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_evap_z2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_evap_z2.setObjectName("label_evap_z2")
        self.gridLayout.addWidget(self.label_evap_z2, 3, 2, 1, 1)
        self.evap_z1_edit = QtWidgets.QLineEdit(self.evap_c)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evap_z1_edit.sizePolicy().hasHeightForWidth())
        self.evap_z1_edit.setSizePolicy(sizePolicy)
        self.evap_z1_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.evap_z1_edit.setObjectName("evap_z1_edit")
        self.gridLayout.addWidget(self.evap_z1_edit, 3, 1, 1, 1)
        self.label_evap_x2 = QtWidgets.QLabel(self.evap_c)
        self.label_evap_x2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_evap_x2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_evap_x2.setObjectName("label_evap_x2")
        self.gridLayout.addWidget(self.label_evap_x2, 1, 2, 1, 1)
        self.choose_evap_btn = QtWidgets.QPushButton(self.evap_c)
        self.choose_evap_btn.setMinimumSize(QtCore.QSize(0, 28))
        self.choose_evap_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.choose_evap_btn.setAutoDefault(False)
        self.choose_evap_btn.setObjectName("choose_evap_btn")
        self.gridLayout.addWidget(self.choose_evap_btn, 4, 3, 1, 1)
        self.label_evap_y2 = QtWidgets.QLabel(self.evap_c)
        self.label_evap_y2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_evap_y2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_evap_y2.setObjectName("label_evap_y2")
        self.gridLayout.addWidget(self.label_evap_y2, 2, 2, 1, 1)
        self.evap_y2_edit = QtWidgets.QLineEdit(self.evap_c)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evap_y2_edit.sizePolicy().hasHeightForWidth())
        self.evap_y2_edit.setSizePolicy(sizePolicy)
        self.evap_y2_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.evap_y2_edit.setObjectName("evap_y2_edit")
        self.gridLayout.addWidget(self.evap_y2_edit, 2, 3, 1, 1)
        self.evap_y1_edit = QtWidgets.QLineEdit(self.evap_c)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evap_y1_edit.sizePolicy().hasHeightForWidth())
        self.evap_y1_edit.setSizePolicy(sizePolicy)
        self.evap_y1_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.evap_y1_edit.setObjectName("evap_y1_edit")
        self.gridLayout.addWidget(self.evap_y1_edit, 2, 1, 1, 1)
        self.evap_x1_edit = QtWidgets.QLineEdit(self.evap_c)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evap_x1_edit.sizePolicy().hasHeightForWidth())
        self.evap_x1_edit.setSizePolicy(sizePolicy)
        self.evap_x1_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.evap_x1_edit.setObjectName("evap_x1_edit")
        self.gridLayout.addWidget(self.evap_x1_edit, 1, 1, 1, 1)
        self.label_evap_C1 = QtWidgets.QLabel(self.evap_c)
        self.label_evap_C1.setMinimumSize(QtCore.QSize(100, 0))
        self.label_evap_C1.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_evap_C1.setObjectName("label_evap_C1")
        self.gridLayout.addWidget(self.label_evap_C1, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.evap_c)
        self.hc_c = QtWidgets.QGroupBox(self.requisite_c_area)
        self.hc_c.setEnabled(True)
        self.hc_c.setMinimumSize(QtCore.QSize(0, 180))
        self.hc_c.setMaximumSize(QtCore.QSize(16777215, 185))
        self.hc_c.setObjectName("hc_c")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.hc_c)
        self.gridLayout_2.setContentsMargins(40, 10, 40, 10)
        self.gridLayout_2.setHorizontalSpacing(40)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_hc_y2 = QtWidgets.QLabel(self.hc_c)
        self.label_hc_y2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_hc_y2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_hc_y2.setObjectName("label_hc_y2")
        self.gridLayout_2.addWidget(self.label_hc_y2, 2, 2, 1, 1)
        self.hc_c1_edit = QtWidgets.QLineEdit(self.hc_c)
        self.hc_c1_edit.setMinimumSize(QtCore.QSize(0, 22))
        self.hc_c1_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.hc_c1_edit.setObjectName("hc_c1_edit")
        self.gridLayout_2.addWidget(self.hc_c1_edit, 0, 1, 1, 1)
        self.hc_y1_edit = QtWidgets.QLineEdit(self.hc_c)
        self.hc_y1_edit.setMinimumSize(QtCore.QSize(0, 22))
        self.hc_y1_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.hc_y1_edit.setObjectName("hc_y1_edit")
        self.gridLayout_2.addWidget(self.hc_y1_edit, 2, 1, 1, 1)
        self.label_hc_y1 = QtWidgets.QLabel(self.hc_c)
        self.label_hc_y1.setMinimumSize(QtCore.QSize(100, 0))
        self.label_hc_y1.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_hc_y1.setObjectName("label_hc_y1")
        self.gridLayout_2.addWidget(self.label_hc_y1, 2, 0, 1, 1)
        self.label_hc_z2 = QtWidgets.QLabel(self.hc_c)
        self.label_hc_z2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_hc_z2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_hc_z2.setObjectName("label_hc_z2")
        self.gridLayout_2.addWidget(self.label_hc_z2, 3, 2, 1, 1)
        self.hc_y2_edit = QtWidgets.QLineEdit(self.hc_c)
        self.hc_y2_edit.setMinimumSize(QtCore.QSize(0, 22))
        self.hc_y2_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.hc_y2_edit.setObjectName("hc_y2_edit")
        self.gridLayout_2.addWidget(self.hc_y2_edit, 2, 3, 1, 1)
        self.hc_c2_edit = QtWidgets.QLineEdit(self.hc_c)
        self.hc_c2_edit.setMinimumSize(QtCore.QSize(0, 22))
        self.hc_c2_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.hc_c2_edit.setObjectName("hc_c2_edit")
        self.gridLayout_2.addWidget(self.hc_c2_edit, 0, 3, 1, 1)
        self.hc_x2_edit = QtWidgets.QLineEdit(self.hc_c)
        self.hc_x2_edit.setMinimumSize(QtCore.QSize(0, 22))
        self.hc_x2_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.hc_x2_edit.setObjectName("hc_x2_edit")
        self.gridLayout_2.addWidget(self.hc_x2_edit, 1, 3, 1, 1)
        self.hc_x1_edit = QtWidgets.QLineEdit(self.hc_c)
        self.hc_x1_edit.setMinimumSize(QtCore.QSize(0, 22))
        self.hc_x1_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.hc_x1_edit.setObjectName("hc_x1_edit")
        self.gridLayout_2.addWidget(self.hc_x1_edit, 1, 1, 1, 1)
        self.choose_hc_btn = QtWidgets.QPushButton(self.hc_c)
        self.choose_hc_btn.setMinimumSize(QtCore.QSize(0, 28))
        self.choose_hc_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.choose_hc_btn.setAutoDefault(False)
        self.choose_hc_btn.setObjectName("choose_hc_btn")
        self.gridLayout_2.addWidget(self.choose_hc_btn, 4, 3, 1, 1)
        self.label_hc_x2 = QtWidgets.QLabel(self.hc_c)
        self.label_hc_x2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_hc_x2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_hc_x2.setObjectName("label_hc_x2")
        self.gridLayout_2.addWidget(self.label_hc_x2, 1, 2, 1, 1)
        self.label_hc_x1 = QtWidgets.QLabel(self.hc_c)
        self.label_hc_x1.setMinimumSize(QtCore.QSize(100, 0))
        self.label_hc_x1.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_hc_x1.setObjectName("label_hc_x1")
        self.gridLayout_2.addWidget(self.label_hc_x1, 1, 0, 1, 1)
        self.label_hc_C2 = QtWidgets.QLabel(self.hc_c)
        self.label_hc_C2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_hc_C2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_hc_C2.setObjectName("label_hc_C2")
        self.gridLayout_2.addWidget(self.label_hc_C2, 0, 2, 1, 1)
        self.hc_z2_edit = QtWidgets.QLineEdit(self.hc_c)
        self.hc_z2_edit.setMinimumSize(QtCore.QSize(0, 22))
        self.hc_z2_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.hc_z2_edit.setObjectName("hc_z2_edit")
        self.gridLayout_2.addWidget(self.hc_z2_edit, 3, 3, 1, 1)
        self.label_hc_C1 = QtWidgets.QLabel(self.hc_c)
        self.label_hc_C1.setMinimumSize(QtCore.QSize(100, 0))
        self.label_hc_C1.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_hc_C1.setObjectName("label_hc_C1")
        self.gridLayout_2.addWidget(self.label_hc_C1, 0, 0, 1, 1)
        self.hc_z1_edit = QtWidgets.QLineEdit(self.hc_c)
        self.hc_z1_edit.setMinimumSize(QtCore.QSize(0, 22))
        self.hc_z1_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.hc_z1_edit.setObjectName("hc_z1_edit")
        self.gridLayout_2.addWidget(self.hc_z1_edit, 3, 1, 1, 1)
        self.label_hc_z1 = QtWidgets.QLabel(self.hc_c)
        self.label_hc_z1.setMinimumSize(QtCore.QSize(100, 0))
        self.label_hc_z1.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_hc_z1.setObjectName("label_hc_z1")
        self.gridLayout_2.addWidget(self.label_hc_z1, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.hc_c)
        self.valve_c = QtWidgets.QGroupBox(self.requisite_c_area)
        self.valve_c.setObjectName("valve_c")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.valve_c)
        self.gridLayout_4.setContentsMargins(40, 10, 40, 10)
        self.gridLayout_4.setHorizontalSpacing(40)
        self.gridLayout_4.setVerticalSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.valve_ox_label = QtWidgets.QLabel(self.valve_c)
        self.valve_ox_label.setMinimumSize(QtCore.QSize(100, 0))
        self.valve_ox_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.valve_ox_label.setObjectName("valve_ox_label")
        self.gridLayout_4.addWidget(self.valve_ox_label, 0, 0, 1, 1)
        self.valve_ox_edit = QtWidgets.QLineEdit(self.valve_c)
        self.valve_ox_edit.setMinimumSize(QtCore.QSize(132, 22))
        self.valve_ox_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.valve_ox_edit.setObjectName("valve_ox_edit")
        self.gridLayout_4.addWidget(self.valve_ox_edit, 0, 1, 1, 1)
        self.valve_dx_label = QtWidgets.QLabel(self.valve_c)
        self.valve_dx_label.setMinimumSize(QtCore.QSize(100, 0))
        self.valve_dx_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.valve_dx_label.setObjectName("valve_dx_label")
        self.gridLayout_4.addWidget(self.valve_dx_label, 0, 2, 1, 1)
        self.valve_dx_edit = QtWidgets.QLineEdit(self.valve_c)
        self.valve_dx_edit.setMinimumSize(QtCore.QSize(132, 22))
        self.valve_dx_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.valve_dx_edit.setObjectName("valve_dx_edit")
        self.gridLayout_4.addWidget(self.valve_dx_edit, 0, 3, 1, 1)
        self.valve_oy_label = QtWidgets.QLabel(self.valve_c)
        self.valve_oy_label.setMinimumSize(QtCore.QSize(100, 0))
        self.valve_oy_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.valve_oy_label.setObjectName("valve_oy_label")
        self.gridLayout_4.addWidget(self.valve_oy_label, 1, 0, 1, 1)
        self.valve_oy_edit = QtWidgets.QLineEdit(self.valve_c)
        self.valve_oy_edit.setMinimumSize(QtCore.QSize(132, 22))
        self.valve_oy_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.valve_oy_edit.setObjectName("valve_oy_edit")
        self.gridLayout_4.addWidget(self.valve_oy_edit, 1, 1, 1, 1)
        self.valve_dy_label = QtWidgets.QLabel(self.valve_c)
        self.valve_dy_label.setMinimumSize(QtCore.QSize(100, 0))
        self.valve_dy_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.valve_dy_label.setObjectName("valve_dy_label")
        self.gridLayout_4.addWidget(self.valve_dy_label, 1, 2, 1, 1)
        self.valve_dy_edit = QtWidgets.QLineEdit(self.valve_c)
        self.valve_dy_edit.setMinimumSize(QtCore.QSize(132, 22))
        self.valve_dy_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.valve_dy_edit.setObjectName("valve_dy_edit")
        self.gridLayout_4.addWidget(self.valve_dy_edit, 1, 3, 1, 1)
        self.valve_oz_label = QtWidgets.QLabel(self.valve_c)
        self.valve_oz_label.setMinimumSize(QtCore.QSize(100, 0))
        self.valve_oz_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.valve_oz_label.setObjectName("valve_oz_label")
        self.gridLayout_4.addWidget(self.valve_oz_label, 2, 0, 1, 1)
        self.valve_oz_edit = QtWidgets.QLineEdit(self.valve_c)
        self.valve_oz_edit.setMinimumSize(QtCore.QSize(132, 22))
        self.valve_oz_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.valve_oz_edit.setObjectName("valve_oz_edit")
        self.gridLayout_4.addWidget(self.valve_oz_edit, 2, 1, 1, 1)
        self.valve_dz_label = QtWidgets.QLabel(self.valve_c)
        self.valve_dz_label.setMinimumSize(QtCore.QSize(100, 0))
        self.valve_dz_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.valve_dz_label.setObjectName("valve_dz_label")
        self.gridLayout_4.addWidget(self.valve_dz_label, 2, 2, 1, 1)
        self.valve_dz_edit = QtWidgets.QLineEdit(self.valve_c)
        self.valve_dz_edit.setMinimumSize(QtCore.QSize(132, 22))
        self.valve_dz_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.valve_dz_edit.setObjectName("valve_dz_edit")
        self.gridLayout_4.addWidget(self.valve_dz_edit, 2, 3, 1, 1)
        self.valve_td_label = QtWidgets.QLabel(self.valve_c)
        self.valve_td_label.setMinimumSize(QtCore.QSize(100, 0))
        self.valve_td_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.valve_td_label.setObjectName("valve_td_label")
        self.gridLayout_4.addWidget(self.valve_td_label, 3, 0, 1, 1)
        self.valve_td_edit = QtWidgets.QLineEdit(self.valve_c)
        self.valve_td_edit.setMinimumSize(QtCore.QSize(132, 22))
        self.valve_td_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.valve_td_edit.setObjectName("valve_td_edit")
        self.gridLayout_4.addWidget(self.valve_td_edit, 3, 1, 1, 1)
        self.valve_rp_label = QtWidgets.QLabel(self.valve_c)
        self.valve_rp_label.setMinimumSize(QtCore.QSize(100, 0))
        self.valve_rp_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.valve_rp_label.setObjectName("valve_rp_label")
        self.gridLayout_4.addWidget(self.valve_rp_label, 3, 2, 1, 1)
        self.valve_rp_edit = QtWidgets.QLineEdit(self.valve_c)
        self.valve_rp_edit.setMinimumSize(QtCore.QSize(132, 22))
        self.valve_rp_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.valve_rp_edit.setObjectName("valve_rp_edit")
        self.gridLayout_4.addWidget(self.valve_rp_edit, 3, 3, 1, 1)
        self.valve_sa_label = QtWidgets.QLabel(self.valve_c)
        self.valve_sa_label.setMinimumSize(QtCore.QSize(100, 0))
        self.valve_sa_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.valve_sa_label.setObjectName("valve_sa_label")
        self.gridLayout_4.addWidget(self.valve_sa_label, 4, 0, 1, 1)
        self.valve_sa_edit = QtWidgets.QLineEdit(self.valve_c)
        self.valve_sa_edit.setMinimumSize(QtCore.QSize(132, 22))
        self.valve_sa_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.valve_sa_edit.setObjectName("valve_sa_edit")
        self.gridLayout_4.addWidget(self.valve_sa_edit, 4, 1, 1, 1)
        self.valve_fa_label = QtWidgets.QLabel(self.valve_c)
        self.valve_fa_label.setMinimumSize(QtCore.QSize(100, 0))
        self.valve_fa_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.valve_fa_label.setObjectName("valve_fa_label")
        self.gridLayout_4.addWidget(self.valve_fa_label, 4, 2, 1, 1)
        self.valve_fa_edit = QtWidgets.QLineEdit(self.valve_c)
        self.valve_fa_edit.setMinimumSize(QtCore.QSize(132, 22))
        self.valve_fa_edit.setMaximumSize(QtCore.QSize(132, 24))
        self.valve_fa_edit.setObjectName("valve_fa_edit")
        self.gridLayout_4.addWidget(self.valve_fa_edit, 4, 3, 1, 1)
        self.verticalLayout.addWidget(self.valve_c)
        self.temp_c = QtWidgets.QGroupBox(self.requisite_c_area)
        self.temp_c.setObjectName("temp_c")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.temp_c)
        self.horizontalLayout_3.setContentsMargins(40, 10, 40, 10)
        self.horizontalLayout_3.setSpacing(40)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.temp_inlet_label = QtWidgets.QLabel(self.temp_c)
        self.temp_inlet_label.setMinimumSize(QtCore.QSize(100, 0))
        self.temp_inlet_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.temp_inlet_label.setObjectName("temp_inlet_label")
        self.horizontalLayout_3.addWidget(self.temp_inlet_label)
        self.temp_inlet_edit = QtWidgets.QLineEdit(self.temp_c)
        self.temp_inlet_edit.setMinimumSize(QtCore.QSize(132, 0))
        self.temp_inlet_edit.setMaximumSize(QtCore.QSize(132, 16777215))
        self.temp_inlet_edit.setObjectName("temp_inlet_edit")
        self.horizontalLayout_3.addWidget(self.temp_inlet_edit)
        self.temp_hc_label = QtWidgets.QLabel(self.temp_c)
        self.temp_hc_label.setMinimumSize(QtCore.QSize(100, 0))
        self.temp_hc_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.temp_hc_label.setObjectName("temp_hc_label")
        self.horizontalLayout_3.addWidget(self.temp_hc_label)
        self.temp_hc_edit = QtWidgets.QLineEdit(self.temp_c)
        self.temp_hc_edit.setMaximumSize(QtCore.QSize(132, 16777215))
        self.temp_hc_edit.setSizeIncrement(QtCore.QSize(132, 0))
        self.temp_hc_edit.setObjectName("temp_hc_edit")
        self.horizontalLayout_3.addWidget(self.temp_hc_edit)
        self.verticalLayout.addWidget(self.temp_c)
        self.scrollArea.setWidget(self.requisite_c_area)
        self.interact_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.interact_edit.setGeometry(QtCore.QRect(10, 500, 711, 161))
        self.interact_edit.setObjectName("interact_edit")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 911, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.project_mainHlayout = QtWidgets.QHBoxLayout()
        self.project_mainHlayout.setObjectName("project_mainHlayout")
        self.project_le_layout = QtWidgets.QVBoxLayout()
        self.project_le_layout.setContentsMargins(10, -1, -1, -1)
        self.project_le_layout.setObjectName("project_le_layout")
        self.project_le1_layout = QtWidgets.QHBoxLayout()
        self.project_le1_layout.setContentsMargins(0, -1, -1, -1)
        self.project_le1_layout.setSpacing(10)
        self.project_le1_layout.setObjectName("project_le1_layout")
        self.project_name_label = QtWidgets.QLabel(self.layoutWidget)
        self.project_name_label.setMinimumSize(QtCore.QSize(40, 0))
        self.project_name_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.project_name_label.setObjectName("project_name_label")
        self.project_le1_layout.addWidget(self.project_name_label)
        self.project_name_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.project_name_edit.setMinimumSize(QtCore.QSize(70, 26))
        self.project_name_edit.setMaximumSize(QtCore.QSize(100, 26))
        self.project_name_edit.setObjectName("project_name_edit")
        self.project_le1_layout.addWidget(self.project_name_edit)
        self.version_name_label = QtWidgets.QLabel(self.layoutWidget)
        self.version_name_label.setMinimumSize(QtCore.QSize(30, 26))
        self.version_name_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.version_name_label.setObjectName("version_name_label")
        self.project_le1_layout.addWidget(self.version_name_label)
        self.version_name_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.version_name_edit.setMinimumSize(QtCore.QSize(70, 26))
        self.version_name_edit.setMaximumSize(QtCore.QSize(100, 26))
        self.version_name_edit.setObjectName("version_name_edit")
        self.project_le1_layout.addWidget(self.version_name_edit)
        self.version_date_ = QtWidgets.QLabel(self.layoutWidget)
        self.version_date_.setMinimumSize(QtCore.QSize(55, 0))
        self.version_date_.setMaximumSize(QtCore.QSize(60, 30))
        self.version_date_.setObjectName("version_date_")
        self.project_le1_layout.addWidget(self.version_date_)
        self.version_date_edit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.version_date_edit.sizePolicy().hasHeightForWidth())
        self.version_date_edit.setSizePolicy(sizePolicy)
        self.version_date_edit.setMinimumSize(QtCore.QSize(70, 26))
        self.version_date_edit.setMaximumSize(QtCore.QSize(100, 26))
        self.version_date_edit.setObjectName("version_date_edit")
        self.project_le1_layout.addWidget(self.version_date_edit)
        self.project_le_layout.addLayout(self.project_le1_layout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.project_address_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_address_label.sizePolicy().hasHeightForWidth())
        self.project_address_label.setSizePolicy(sizePolicy)
        self.project_address_label.setMinimumSize(QtCore.QSize(60, 26))
        self.project_address_label.setObjectName("project_address_label")
        self.horizontalLayout_2.addWidget(self.project_address_label)
        self.project_address_edit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_address_edit.sizePolicy().hasHeightForWidth())
        self.project_address_edit.setSizePolicy(sizePolicy)
        self.project_address_edit.setMinimumSize(QtCore.QSize(400, 26))
        self.project_address_edit.setMaximumSize(QtCore.QSize(410, 16777215))
        self.project_address_edit.setObjectName("project_address_edit")
        self.horizontalLayout_2.addWidget(self.project_address_edit)
        self.project_address_explore = QtWidgets.QToolButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../fluent_gui/icon/explore_file.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.project_address_explore.setIcon(icon1)
        self.project_address_explore.setIconSize(QtCore.QSize(25, 20))
        self.project_address_explore.setObjectName("project_address_explore")
        self.horizontalLayout_2.addWidget(self.project_address_explore)
        self.project_le_layout.addLayout(self.horizontalLayout_2)
        self.project_mainHlayout.addLayout(self.project_le_layout)
        self.horizontalLayout.addLayout(self.project_mainHlayout)
        spacerItem1 = QtWidgets.QSpacerItem(50, 39, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.show_workflow_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.show_workflow_btn.setMinimumSize(QtCore.QSize(100, 30))
        self.show_workflow_btn.setObjectName("show_workflow_btn")
        self.verticalLayout_2.addWidget(self.show_workflow_btn)
        self.return_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.return_btn.setMinimumSize(QtCore.QSize(100, 30))
        self.return_btn.setObjectName("return_btn")
        self.verticalLayout_2.addWidget(self.return_btn)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.account_box = QtWidgets.QGroupBox(self.layoutWidget)
        self.account_box.setMinimumSize(QtCore.QSize(180, 0))
        self.account_box.setObjectName("account_box")
        self.username_label = QtWidgets.QLabel(self.account_box)
        self.username_label.setGeometry(QtCore.QRect(10, 20, 200, 41))
        self.username_label.setMinimumSize(QtCore.QSize(200, 0))
        self.username_label.setObjectName("username_label")
        self.horizontalLayout.addWidget(self.account_box)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(730, 500, 211, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.start_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.start_btn.setMinimumSize(QtCore.QSize(150, 70))
        self.start_btn.setMaximumSize(QtCore.QSize(200, 150))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout_3.addWidget(self.start_btn)
        self.solver_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.solver_btn.setMinimumSize(QtCore.QSize(150, 70))
        self.solver_btn.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.solver_btn.setFont(font)
        self.solver_btn.setObjectName("solver_btn")
        self.verticalLayout_3.addWidget(self.solver_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 951, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuadvance = QtWidgets.QMenu(self.menubar)
        self.menuadvance.setObjectName("menuadvance")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionexport = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../fluent_gui/icon/文件导出.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionexport.setIcon(icon2)
        self.actionexport.setObjectName("actionexport")
        self.actionimport = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../fluent_gui/icon/import.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionimport.setIcon(icon3)
        self.actionimport.setObjectName("actionimport")
        self.actionalter_default_parameter = QtWidgets.QAction(MainWindow)
        self.actionalter_default_parameter.setObjectName("actionalter_default_parameter")
        self.actionsolve = QtWidgets.QAction(MainWindow)
        self.actionsolve.setObjectName("actionsolve")
        self.menufile.addAction(self.actionimport)
        self.menufile.addAction(self.actionexport)
        self.menuadvance.addAction(self.actionalter_default_parameter)
        self.menuadvance.addAction(self.actionsolve)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuadvance.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.actionimport)
        self.toolBar.addAction(self.actionexport)
        self.label_inlet_number.setBuddy(self.inlet_number)
        self.label_outlet_number.setBuddy(self.outlet_number)
        self.label_distrib_number.setBuddy(self.distrib_number)
        self.mass_inlet_label.setBuddy(self.mass_inlet_edit)
        self.label_evap_x1.setBuddy(self.evap_x1_edit)
        self.label_evap_C2.setBuddy(self.evap_c2_edit)
        self.label_evap_z1.setBuddy(self.evap_z1_edit)
        self.label_evap_y1.setBuddy(self.evap_y1_edit)
        self.label_evap_z2.setBuddy(self.evap_z2_edit)
        self.label_evap_x2.setBuddy(self.evap_x2_edit)
        self.label_evap_y2.setBuddy(self.evap_y2_edit)
        self.label_evap_C1.setBuddy(self.evap_c1_edit)
        self.label_hc_y2.setBuddy(self.evap_y2_edit)
        self.label_hc_y1.setBuddy(self.evap_y1_edit)
        self.label_hc_z2.setBuddy(self.evap_z2_edit)
        self.label_hc_x2.setBuddy(self.evap_x2_edit)
        self.label_hc_x1.setBuddy(self.evap_x1_edit)
        self.label_hc_C2.setBuddy(self.evap_c2_edit)
        self.label_hc_C1.setBuddy(self.evap_c1_edit)
        self.label_hc_z1.setBuddy(self.evap_z1_edit)
        self.valve_ox_label.setBuddy(self.valve_ox_edit)
        self.valve_dx_label.setBuddy(self.valve_dx_edit)
        self.valve_oy_label.setBuddy(self.valve_oy_edit)
        self.valve_dy_label.setBuddy(self.valve_dy_edit)
        self.valve_oz_label.setBuddy(self.valve_oz_edit)
        self.valve_dz_label.setBuddy(self.valve_dz_edit)
        self.valve_td_label.setBuddy(self.valve_td_edit)
        self.valve_rp_label.setBuddy(self.valve_rp_edit)
        self.valve_sa_label.setBuddy(self.valve_sa_edit)
        self.valve_fa_label.setBuddy(self.valve_fa_edit)
        self.project_name_label.setBuddy(self.project_name_edit)
        self.version_name_label.setBuddy(self.version_name_edit)
        self.version_date_.setBuddy(self.version_date_edit)
        self.project_address_label.setBuddy(self.project_address_edit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.project_name_edit, self.version_name_edit)
        MainWindow.setTabOrder(self.version_name_edit, self.version_date_edit)
        MainWindow.setTabOrder(self.version_date_edit, self.project_address_edit)
        MainWindow.setTabOrder(self.project_address_edit, self.project_address_explore)
        MainWindow.setTabOrder(self.project_address_explore, self.inlet_number)
        MainWindow.setTabOrder(self.inlet_number, self.outlet_number)
        MainWindow.setTabOrder(self.outlet_number, self.distrib_number)
        MainWindow.setTabOrder(self.distrib_number, self.part_tree)
        MainWindow.setTabOrder(self.part_tree, self.energy_checkbox)
        MainWindow.setTabOrder(self.energy_checkbox, self.quick_distribfc_btn)
        MainWindow.setTabOrder(self.quick_distribfc_btn, self.quick_distribfh_btn)
        MainWindow.setTabOrder(self.quick_distribfh_btn, self.quick_distribbil_btn)
        MainWindow.setTabOrder(self.quick_distribbil_btn, self.quick_distriblin_btn)
        MainWindow.setTabOrder(self.quick_distriblin_btn, self.finish_mode_info_btn)
        MainWindow.setTabOrder(self.finish_mode_info_btn, self.mass_inlet_edit)
        MainWindow.setTabOrder(self.mass_inlet_edit, self.unit_btn)
        MainWindow.setTabOrder(self.unit_btn, self.evap_c1_edit)
        MainWindow.setTabOrder(self.evap_c1_edit, self.evap_c2_edit)
        MainWindow.setTabOrder(self.evap_c2_edit, self.evap_x1_edit)
        MainWindow.setTabOrder(self.evap_x1_edit, self.evap_y1_edit)
        MainWindow.setTabOrder(self.evap_y1_edit, self.evap_z1_edit)
        MainWindow.setTabOrder(self.evap_z1_edit, self.evap_x2_edit)
        MainWindow.setTabOrder(self.evap_x2_edit, self.evap_y2_edit)
        MainWindow.setTabOrder(self.evap_y2_edit, self.evap_z2_edit)
        MainWindow.setTabOrder(self.evap_z2_edit, self.choose_evap_btn)
        MainWindow.setTabOrder(self.choose_evap_btn, self.hc_c1_edit)
        MainWindow.setTabOrder(self.hc_c1_edit, self.hc_c2_edit)
        MainWindow.setTabOrder(self.hc_c2_edit, self.hc_x1_edit)
        MainWindow.setTabOrder(self.hc_x1_edit, self.hc_y1_edit)
        MainWindow.setTabOrder(self.hc_y1_edit, self.hc_z1_edit)
        MainWindow.setTabOrder(self.hc_z1_edit, self.hc_x2_edit)
        MainWindow.setTabOrder(self.hc_x2_edit, self.hc_y2_edit)
        MainWindow.setTabOrder(self.hc_y2_edit, self.hc_z2_edit)
        MainWindow.setTabOrder(self.hc_z2_edit, self.choose_hc_btn)
        MainWindow.setTabOrder(self.choose_hc_btn, self.valve_ox_edit)
        MainWindow.setTabOrder(self.valve_ox_edit, self.valve_oy_edit)
        MainWindow.setTabOrder(self.valve_oy_edit, self.valve_oz_edit)
        MainWindow.setTabOrder(self.valve_oz_edit, self.valve_dx_edit)
        MainWindow.setTabOrder(self.valve_dx_edit, self.valve_dy_edit)
        MainWindow.setTabOrder(self.valve_dy_edit, self.valve_dz_edit)
        MainWindow.setTabOrder(self.valve_dz_edit, self.valve_td_edit)
        MainWindow.setTabOrder(self.valve_td_edit, self.valve_rp_edit)
        MainWindow.setTabOrder(self.valve_rp_edit, self.valve_sa_edit)
        MainWindow.setTabOrder(self.valve_sa_edit, self.valve_fa_edit)
        MainWindow.setTabOrder(self.valve_fa_edit, self.interact_edit)
        MainWindow.setTabOrder(self.interact_edit, self.show_workflow_btn)
        MainWindow.setTabOrder(self.show_workflow_btn, self.start_btn)
        MainWindow.setTabOrder(self.start_btn, self.return_btn)
        MainWindow.setTabOrder(self.return_btn, self.scrollArea)
        MainWindow.setTabOrder(self.scrollArea, self.solver_btn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CFD-GUI"))
        self.finish_mode_info_btn.setText(_translate("MainWindow", "启动CAD"))
        self.part_tree.headerItem().setText(0, _translate("MainWindow", "模型部件"))
        __sortingEnabled = self.part_tree.isSortingEnabled()
        self.part_tree.setSortingEnabled(False)
        self.part_tree.topLevelItem(0).setText(0, _translate("MainWindow", "进口半球（inlet_sphere)"))
        self.part_tree.topLevelItem(1).setText(0, _translate("MainWindow", "进口(ai)"))
        self.part_tree.topLevelItem(2).setText(0, _translate("MainWindow", "过滤芯(filter)"))
        self.part_tree.topLevelItem(3).setText(0, _translate("MainWindow", "导流段(cone)"))
        self.part_tree.topLevelItem(4).setText(0, _translate("MainWindow", "蜗壳(volute)"))
        self.part_tree.topLevelItem(5).setText(0, _translate("MainWindow", "叶轮(fan)"))
        self.part_tree.topLevelItem(6).setText(0, _translate("MainWindow", "扩张段(diffuser)"))
        self.part_tree.topLevelItem(7).setText(0, _translate("MainWindow", "蒸发器(evap)"))
        self.part_tree.topLevelItem(8).setText(0, _translate("MainWindow", "分配箱(distrib)"))
        self.part_tree.topLevelItem(9).setText(0, _translate("MainWindow", "加热芯(heater)"))
        self.part_tree.topLevelItem(10).setText(0, _translate("MainWindow", "PTC"))
        self.part_tree.topLevelItem(11).setText(0, _translate("MainWindow", "转动风门"))
        self.part_tree.setSortingEnabled(__sortingEnabled)
        self.label_inlet_number.setText(_translate("MainWindow", "进口数量"))
        self.label_outlet_number.setText(_translate("MainWindow", "出口数量"))
        self.label_distrib_number.setText(_translate("MainWindow", "分配箱数量"))
        self.quick_mode_box.setTitle(_translate("MainWindow", "快速模板"))
        self.energy_checkbox.setText(_translate("MainWindow", "启用温度计算"))
        self.quick_distribfc_btn.setText(_translate("MainWindow", "全冷分配箱"))
        self.quick_distribfh_btn.setText(_translate("MainWindow", "全热分配箱"))
        self.quick_distribbil_btn.setText(_translate("MainWindow", "Bi-L 分配箱"))
        self.quick_distriblin_btn.setText(_translate("MainWindow", "线性分配箱"))
        self.mass_inlet.setTitle(_translate("MainWindow", "进口流量"))
        self.mass_inlet_label.setText(_translate("MainWindow", "质量流（Kg/s)"))
        self.unit_btn.setText(_translate("MainWindow", "单位转换器"))
        self.evap_c.setTitle(_translate("MainWindow", "蒸发器参数"))
        self.label_evap_x1.setText(_translate("MainWindow", "气流方向X1"))
        self.label_evap_C2.setText(_translate("MainWindow", "惯性阻力系数C2"))
        self.label_evap_z1.setText(_translate("MainWindow", "气流方向Z1"))
        self.label_evap_y1.setText(_translate("MainWindow", "气流方向Y1"))
        self.label_evap_z2.setText(_translate("MainWindow", "侧面方向Z2"))
        self.label_evap_x2.setText(_translate("MainWindow", "侧面方向X2"))
        self.choose_evap_btn.setText(_translate("MainWindow", "选择芯体型号"))
        self.label_evap_y2.setText(_translate("MainWindow", "侧面方向Y2"))
        self.label_evap_C1.setText(_translate("MainWindow", "粘性阻力系数C1"))
        self.hc_c.setTitle(_translate("MainWindow", "加热芯参数"))
        self.label_hc_y2.setText(_translate("MainWindow", "侧面方向Y2"))
        self.label_hc_y1.setText(_translate("MainWindow", "气流方向Y1"))
        self.label_hc_z2.setText(_translate("MainWindow", "侧面方向Z2"))
        self.choose_hc_btn.setText(_translate("MainWindow", "选择芯体型号"))
        self.label_hc_x2.setText(_translate("MainWindow", "侧面方向X2"))
        self.label_hc_x1.setText(_translate("MainWindow", "气流方向X1"))
        self.label_hc_C2.setText(_translate("MainWindow", "惯性阻力系数C2"))
        self.label_hc_C1.setText(_translate("MainWindow", "粘性阻力系数C1"))
        self.label_hc_z1.setText(_translate("MainWindow", "气流方向Z1"))
        self.valve_c.setTitle(_translate("MainWindow", "风门转动参数"))
        self.valve_ox_label.setText(_translate("MainWindow", "轴原点X"))
        self.valve_dx_label.setText(_translate("MainWindow", "轴方向X"))
        self.valve_oy_label.setText(_translate("MainWindow", "轴原点Y"))
        self.valve_dy_label.setText(_translate("MainWindow", "轴方向Y"))
        self.valve_oz_label.setText(_translate("MainWindow", "轴原点Z"))
        self.valve_dz_label.setText(_translate("MainWindow", "轴方向Z"))
        self.valve_td_label.setText(_translate("MainWindow", "总行程(°)"))
        self.valve_rp_label.setText(_translate("MainWindow", "每转比例(%)"))
        self.valve_sa_label.setText(_translate("MainWindow", "起始(°)"))
        self.valve_fa_label.setText(_translate("MainWindow", "结束(°)"))
        self.temp_c.setTitle(_translate("MainWindow", "温度参数"))
        self.temp_inlet_label.setText(_translate("MainWindow", "进口温度 (°)"))
        self.temp_hc_label.setText(_translate("MainWindow", "加热芯温度 (°)"))
        self.project_name_label.setText(_translate("MainWindow", "项目名"))
        self.version_name_label.setText(_translate("MainWindow", " 版本号"))
        self.version_name_edit.setText(_translate("MainWindow", "V"))
        self.version_date_.setText(_translate("MainWindow", "版本日期"))
        self.project_address_label.setText(_translate("MainWindow", "项目地址"))
        self.project_address_explore.setText(_translate("MainWindow", "..."))
        self.show_workflow_btn.setText(_translate("MainWindow", "显示流程"))
        self.return_btn.setText(_translate("MainWindow", "返回"))
        self.account_box.setTitle(_translate("MainWindow", "账户信息"))
        self.username_label.setText(_translate("MainWindow", "TextLabel"))
        self.start_btn.setText(_translate("MainWindow", "开    始"))
        self.solver_btn.setText(_translate("MainWindow", "计    算"))
        self.menufile.setTitle(_translate("MainWindow", "文件"))
        self.menuadvance.setTitle(_translate("MainWindow", "高级"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionexport.setText(_translate("MainWindow", "导出模板"))
        self.actionexport.setToolTip(_translate("MainWindow", "导出模板"))
        self.actionexport.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionimport.setText(_translate("MainWindow", "导入模板"))
        self.actionimport.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionalter_default_parameter.setText(_translate("MainWindow", "显示默认参数"))
        self.actionsolve.setText(_translate("MainWindow", "补算模式"))
