# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_k_test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_k_form(object):
    def setupUi(self, k_form):
        k_form.setObjectName("k_form")
        k_form.resize(727, 461)
        k_form.setMaximumSize(QtCore.QSize(780, 540))
        font = QtGui.QFont()
        font.setPointSize(12)
        k_form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(k_form)
        self.gridLayout.setContentsMargins(40, 30, 40, 40)
        self.gridLayout.setHorizontalSpacing(30)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, -1, 280, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.R_btn = QtWidgets.QRadioButton(k_form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.R_btn.setFont(font)
        self.R_btn.setChecked(False)
        self.R_btn.setObjectName("R_btn")
        self.horizontalLayout.addWidget(self.R_btn)
        self.PQ_btn = QtWidgets.QRadioButton(k_form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PQ_btn.setFont(font)
        self.PQ_btn.setChecked(True)
        self.PQ_btn.setObjectName("PQ_btn")
        self.horizontalLayout.addWidget(self.PQ_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(k_form)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.outlet_tree = QtWidgets.QTreeWidget(k_form)
        self.outlet_tree.setMinimumSize(QtCore.QSize(0, 360))
        self.outlet_tree.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.outlet_tree.setFont(font)
        self.outlet_tree.setObjectName("outlet_tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.outlet_tree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.outlet_tree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.outlet_tree)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        self.gridLayout.addWidget(self.outlet_tree, 1, 0, 2, 1)
        self.k_table = QtWidgets.QTableWidget(k_form)
        self.k_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.k_table.setRowCount(0)
        self.k_table.setObjectName("k_table")
        self.k_table.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.k_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.k_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.k_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.k_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.k_table.setHorizontalHeaderItem(4, item)
        self.k_table.horizontalHeader().setDefaultSectionSize(80)
        self.k_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.k_table, 2, 1, 1, 1)

        self.retranslateUi(k_form)
        QtCore.QMetaObject.connectSlotsByName(k_form)

    def retranslateUi(self, k_form):
        _translate = QtCore.QCoreApplication.translate
        k_form.setWindowTitle(_translate("k_form", "出口与风阻计算器"))
        self.R_btn.setText(_translate("k_form", "R"))
        self.PQ_btn.setText(_translate("k_form", "PQ"))
        self.label.setText(_translate("k_form", "* 请勾选出口，并在右侧表格内填写出口面积，R值或PQ信息，以计算风阻K值"))
        self.outlet_tree.headerItem().setText(0, _translate("k_form", "Outlet"))
        __sortingEnabled = self.outlet_tree.isSortingEnabled()
        self.outlet_tree.setSortingEnabled(False)
        self.outlet_tree.topLevelItem(0).setText(0, _translate("k_form", "vent"))
        self.outlet_tree.topLevelItem(0).child(0).setText(0, _translate("k_form", "outlet_cvl"))
        self.outlet_tree.topLevelItem(0).child(1).setText(0, _translate("k_form", "outlet_cvr"))
        self.outlet_tree.topLevelItem(0).child(2).setText(0, _translate("k_form", "outlet_svl"))
        self.outlet_tree.topLevelItem(0).child(3).setText(0, _translate("k_form", "outlet_svr"))
        self.outlet_tree.topLevelItem(0).child(4).setText(0, _translate("k_form", "outlet_rv"))
        self.outlet_tree.topLevelItem(0).child(5).setText(0, _translate("k_form", "outlet_vent"))
        self.outlet_tree.topLevelItem(1).setText(0, _translate("k_form", "foot"))
        self.outlet_tree.topLevelItem(1).child(0).setText(0, _translate("k_form", "outlet_ffl"))
        self.outlet_tree.topLevelItem(1).child(1).setText(0, _translate("k_form", "outlet_ffr"))
        self.outlet_tree.topLevelItem(1).child(2).setText(0, _translate("k_form", "outlet_rfl"))
        self.outlet_tree.topLevelItem(1).child(3).setText(0, _translate("k_form", "outlet_rfr"))
        self.outlet_tree.topLevelItem(1).child(4).setText(0, _translate("k_form", "outlet_foot"))
        self.outlet_tree.topLevelItem(2).setText(0, _translate("k_form", "defrost"))
        self.outlet_tree.topLevelItem(2).child(0).setText(0, _translate("k_form", "outlet_cdl"))
        self.outlet_tree.topLevelItem(2).child(1).setText(0, _translate("k_form", "outlet_cdr"))
        self.outlet_tree.topLevelItem(2).child(2).setText(0, _translate("k_form", "outlet_sdl"))
        self.outlet_tree.topLevelItem(2).child(3).setText(0, _translate("k_form", "outlet_sdr"))
        self.outlet_tree.setSortingEnabled(__sortingEnabled)
        item = self.k_table.horizontalHeaderItem(0)
        item.setText(_translate("k_form", "S (mm2)"))
        item = self.k_table.horizontalHeaderItem(1)
        item.setText(_translate("k_form", "R "))
        item = self.k_table.horizontalHeaderItem(2)
        item.setText(_translate("k_form", "P (Pa)"))
        item = self.k_table.horizontalHeaderItem(3)
        item.setText(_translate("k_form", "Q (L/s)"))
        item = self.k_table.horizontalHeaderItem(4)
        item.setText(_translate("k_form", "K"))
