# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'porous_model.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame, QVBoxLayout


class MatplotlibWidget(QFrame):
    def __init__(self, parent=None):
        super(MatplotlibWidget, self).__init__(parent)
        self.initUi()

    def initUi(self):
        self.layout = QVBoxLayout(self)
        from subUI.sub_porous_model_fig import MyMplCanvas
        self.mpl = MyMplCanvas(self, width=4, height=2, dpi=70)
        # self.mpl_ntb = NavigationToolbar(self.mpl, self)  # 添加完整的 toolbar

        self.layout.addWidget(self.mpl)
        # self.layout.addWidget(self.mpl_ntb)


class Ui_porous_model_form(object):
    def setupUi(self, porous_model_form):
        porous_model_form.setObjectName("porous_model_form")
        porous_model_form.resize(670, 670)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(porous_model_form.sizePolicy().hasHeightForWidth())
        porous_model_form.setSizePolicy(sizePolicy)
        porous_model_form.setMinimumSize(QtCore.QSize(200, 125))
        porous_model_form.setMaximumSize(QtCore.QSize(670, 670))
        self.gridLayout_2 = QtWidgets.QGridLayout(porous_model_form)
        self.gridLayout_2.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_2.setSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.model_label = QtWidgets.QLabel(porous_model_form)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.model_label.setFont(font)
        self.model_label.setObjectName("model_label")
        self.gridLayout_2.addWidget(self.model_label, 0, 0, 1, 1)
        self.model_combox = QtWidgets.QComboBox(porous_model_form)
        self.model_combox.setMinimumSize(QtCore.QSize(150, 35))
        self.model_combox.setMaximumSize(QtCore.QSize(160, 35))
        self.model_combox.setObjectName("model_combox")
        self.model_combox.addItem("")
        self.gridLayout_2.addWidget(self.model_combox, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(68, 460, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.operate_frame = QtWidgets.QFrame(porous_model_form)
        self.operate_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.operate_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.operate_frame.setObjectName("operate_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.operate_frame)
        self.gridLayout_3.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_3.setHorizontalSpacing(20)
        self.gridLayout_3.setVerticalSpacing(15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.c1_label = QtWidgets.QLabel(self.operate_frame)
        self.c1_label.setObjectName("c1_label")
        self.horizontalLayout.addWidget(self.c1_label)
        self.c1_edit = QtWidgets.QLineEdit(self.operate_frame)
        self.c1_edit.setObjectName("c1_edit")
        self.horizontalLayout.addWidget(self.c1_edit)
        self.c2_label = QtWidgets.QLabel(self.operate_frame)
        self.c2_label.setObjectName("c2_label")
        self.horizontalLayout.addWidget(self.c2_label)
        self.c2_edit = QtWidgets.QLineEdit(self.operate_frame)
        self.c2_edit.setObjectName("c2_edit")
        self.horizontalLayout.addWidget(self.c2_edit)
        self.gridLayout_3.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.model_name_label = QtWidgets.QLabel(self.operate_frame)
        self.model_name_label.setObjectName("model_name_label")
        self.horizontalLayout_3.addWidget(self.model_name_label)
        self.model_name_edit = QtWidgets.QLineEdit(self.operate_frame)
        self.model_name_edit.setObjectName("model_name_edit")
        self.horizontalLayout_3.addWidget(self.model_name_edit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.modify_btn = QtWidgets.QPushButton(self.operate_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modify_btn.sizePolicy().hasHeightForWidth())
        self.modify_btn.setSizePolicy(sizePolicy)
        self.modify_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.modify_btn.setObjectName("modify_btn")
        self.horizontalLayout_2.addWidget(self.modify_btn)
        self.modify_ui_btn = QtWidgets.QPushButton(self.operate_frame)
        self.modify_ui_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.modify_ui_btn.setObjectName("modify_ui_btn")
        self.horizontalLayout_2.addWidget(self.modify_ui_btn)
        self.add_btn = QtWidgets.QPushButton(self.operate_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_btn.sizePolicy().hasHeightForWidth())
        self.add_btn.setSizePolicy(sizePolicy)
        self.add_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_2.addWidget(self.add_btn)
        self.del_btn = QtWidgets.QPushButton(self.operate_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_btn.sizePolicy().hasHeightForWidth())
        self.del_btn.setSizePolicy(sizePolicy)
        self.del_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout_2.addWidget(self.del_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 4, 0, 1, 2)
        self.QP_table = QtWidgets.QTableWidget(self.operate_frame)
        self.QP_table.setMinimumSize(QtCore.QSize(250, 185))
        self.QP_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.QP_table.setAutoScrollMargin(16)
        self.QP_table.setGridStyle(QtCore.Qt.SolidLine)
        self.QP_table.setRowCount(5)
        self.QP_table.setObjectName("QP_table")
        self.QP_table.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.QP_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QP_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.QP_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QP_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.QP_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QP_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.QP_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QP_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.QP_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QP_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.QP_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QP_table.setItem(4, 1, item)
        self.QP_table.horizontalHeader().setDefaultSectionSize(110)
        self.QP_table.horizontalHeader().setMinimumSectionSize(30)
        self.QP_table.horizontalHeader().setStretchLastSection(True)
        self.QP_table.verticalHeader().setDefaultSectionSize(25)
        self.QP_table.verticalHeader().setMinimumSectionSize(25)
        self.QP_table.verticalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.QP_table, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cal_btn = QtWidgets.QPushButton(self.operate_frame)
        self.cal_btn.setMaximumSize(QtCore.QSize(100, 30))
        self.cal_btn.setObjectName("cal_btn")
        self.horizontalLayout_4.addWidget(self.cal_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.effective_dimension_box = QtWidgets.QGroupBox(self.operate_frame)
        self.effective_dimension_box.setObjectName("effective_dimension_box")
        self.gridLayout = QtWidgets.QGridLayout(self.effective_dimension_box)
        self.gridLayout.setObjectName("gridLayout")
        self.width_label = QtWidgets.QLabel(self.effective_dimension_box)
        self.width_label.setObjectName("width_label")
        self.gridLayout.addWidget(self.width_label, 1, 0, 1, 1)
        self.lenth_label = QtWidgets.QLabel(self.effective_dimension_box)
        self.lenth_label.setObjectName("lenth_label")
        self.gridLayout.addWidget(self.lenth_label, 0, 0, 1, 1)
        self.height_edit = QtWidgets.QLineEdit(self.effective_dimension_box)
        self.height_edit.setMinimumSize(QtCore.QSize(60, 25))
        self.height_edit.setObjectName("height_edit")
        self.gridLayout.addWidget(self.height_edit, 2, 1, 1, 1)
        self.height_label = QtWidgets.QLabel(self.effective_dimension_box)
        self.height_label.setObjectName("height_label")
        self.gridLayout.addWidget(self.height_label, 2, 0, 1, 1)
        self.length_edit = QtWidgets.QLineEdit(self.effective_dimension_box)
        self.length_edit.setMinimumSize(QtCore.QSize(60, 25))
        self.length_edit.setObjectName("length_edit")
        self.gridLayout.addWidget(self.length_edit, 0, 1, 1, 1)
        self.width_edit = QtWidgets.QLineEdit(self.effective_dimension_box)
        self.width_edit.setMinimumSize(QtCore.QSize(60, 25))
        self.width_edit.setObjectName("width_edit")
        self.gridLayout.addWidget(self.width_edit, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.effective_dimension_box, 1, 1, 1, 1)
        self.plot_frame = MatplotlibWidget(self.operate_frame)
        self.plot_frame.setMinimumSize(QtCore.QSize(420, 280))
        self.plot_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plot_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plot_frame.setObjectName("plot_frame")
        self.gridLayout_3.addWidget(self.plot_frame, 2, 0, 1, 2)
        self.gridLayout_2.addWidget(self.operate_frame, 0, 1, 5, 1)
        self.load_btn = QtWidgets.QPushButton(porous_model_form)
        self.load_btn.setMaximumSize(QtCore.QSize(140, 16777215))
        self.load_btn.setObjectName("load_btn")
        self.gridLayout_2.addWidget(self.load_btn, 3, 0, 1, 1)

        self.retranslateUi(porous_model_form)
        self.add_btn.clicked.connect(self.modify_ui_btn.hide)
        QtCore.QMetaObject.connectSlotsByName(porous_model_form)

    def retranslateUi(self, porous_model_form):
        _translate = QtCore.QCoreApplication.translate
        porous_model_form.setWindowTitle(_translate("porous_model_form", "型号选择"))
        self.model_label.setText(_translate("porous_model_form", "型号选择"))
        self.model_combox.setItemText(0, _translate("porous_model_form", "添加..."))
        self.c1_label.setText(_translate("porous_model_form", "惯性阻力系数C1"))
        self.c2_label.setText(_translate("porous_model_form", "粘性阻力系数C2"))
        self.model_name_label.setText(_translate("porous_model_form", "型号名称"))
        self.modify_btn.setText(_translate("porous_model_form", "修改"))
        self.modify_ui_btn.setText(_translate("porous_model_form", "修改"))
        self.add_btn.setText(_translate("porous_model_form", "添加"))
        self.del_btn.setText(_translate("porous_model_form", "删除"))
        item = self.QP_table.horizontalHeaderItem(0)
        item.setText(_translate("porous_model_form", "流量(kg/h)"))
        item = self.QP_table.horizontalHeaderItem(1)
        item.setText(_translate("porous_model_form", "压降(Pa)"))
        __sortingEnabled = self.QP_table.isSortingEnabled()
        self.QP_table.setSortingEnabled(False)
        item = self.QP_table.item(0, 0)
        item.setText(_translate("porous_model_form", "202"))
        item = self.QP_table.item(0, 1)
        item.setText(_translate("porous_model_form", "81"))
        item = self.QP_table.item(1, 0)
        item.setText(_translate("porous_model_form", "303"))
        item = self.QP_table.item(1, 1)
        item.setText(_translate("porous_model_form", "144"))
        item = self.QP_table.item(2, 0)
        item.setText(_translate("porous_model_form", "404"))
        item = self.QP_table.item(2, 1)
        item.setText(_translate("porous_model_form", "217"))
        item = self.QP_table.item(3, 0)
        item.setText(_translate("porous_model_form", "505"))
        item = self.QP_table.item(3, 1)
        item.setText(_translate("porous_model_form", "299"))
        item = self.QP_table.item(4, 0)
        item.setText(_translate("porous_model_form", "0"))
        item = self.QP_table.item(4, 1)
        item.setText(_translate("porous_model_form", "0"))
        self.QP_table.setSortingEnabled(__sortingEnabled)
        self.cal_btn.setText(_translate("porous_model_form", "计   算"))
        self.effective_dimension_box.setTitle(_translate("porous_model_form", "有效尺寸"))
        self.width_label.setText(_translate("porous_model_form", "宽(mm)"))
        self.lenth_label.setText(_translate("porous_model_form", "长(mm)"))
        self.height_edit.setText(_translate("porous_model_form", "28"))
        self.height_label.setText(_translate("porous_model_form", "厚度(mm)"))
        self.length_edit.setText(_translate("porous_model_form", "138"))
        self.width_edit.setText(_translate("porous_model_form", "193"))
        self.load_btn.setText(_translate("porous_model_form", "导入"))
