# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_add_project.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget_add(object):
    def setupUi(self, Widget_add):
        Widget_add.setObjectName("Widget_add")
        Widget_add.resize(492, 203)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Widget_add.sizePolicy().hasHeightForWidth())
        Widget_add.setSizePolicy(sizePolicy)
        Widget_add.setMinimumSize(QtCore.QSize(0, 0))
        Widget_add.setLayoutDirection(QtCore.Qt.LeftToRight)
        Widget_add.setStyleSheet("QLineEdit{\n"
"    border:1px solid #778899;\n"
"    border-radius:6px;\n"
"    padding:2px 2px}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Widget_add)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(10, 20, 10, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_simple = QtWidgets.QFrame(Widget_add)
        self.frame_simple.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_simple.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_simple.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_simple.setObjectName("frame_simple")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_simple)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_project_address = QtWidgets.QLabel(self.frame_simple)
        self.label_project_address.setMinimumSize(QtCore.QSize(70, 0))
        self.label_project_address.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_project_address.setObjectName("label_project_address")
        self.horizontalLayout.addWidget(self.label_project_address)
        self.edit_project_address = QtWidgets.QLineEdit(self.frame_simple)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.edit_project_address.sizePolicy().hasHeightForWidth())
        self.edit_project_address.setSizePolicy(sizePolicy)
        self.edit_project_address.setMinimumSize(QtCore.QSize(300, 28))
        self.edit_project_address.setMaximumSize(QtCore.QSize(16777215, 28))
        self.edit_project_address.setObjectName("edit_project_address")
        self.horizontalLayout.addWidget(self.edit_project_address)
        self.btn_project_address = QtWidgets.QToolButton(self.frame_simple)
        self.btn_project_address.setMinimumSize(QtCore.QSize(35, 30))
        self.btn_project_address.setMaximumSize(QtCore.QSize(40, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../.designer/icon/openfile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_project_address.setIcon(icon)
        self.btn_project_address.setIconSize(QtCore.QSize(30, 30))
        self.btn_project_address.setObjectName("btn_project_address")
        self.horizontalLayout.addWidget(self.btn_project_address)
        self.verticalLayout.addWidget(self.frame_simple)
        self.frame_advanced = QtWidgets.QFrame(Widget_add)
        self.frame_advanced.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_advanced.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_advanced.setObjectName("frame_advanced")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_advanced)
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_iteration = QtWidgets.QLabel(self.frame_advanced)
        self.label_iteration.setMinimumSize(QtCore.QSize(70, 0))
        self.label_iteration.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_iteration.setObjectName("label_iteration")
        self.horizontalLayout_4.addWidget(self.label_iteration)
        self.edit_iteration = QtWidgets.QLineEdit(self.frame_advanced)
        self.edit_iteration.setMinimumSize(QtCore.QSize(0, 28))
        self.edit_iteration.setMaximumSize(QtCore.QSize(100, 28))
        self.edit_iteration.setObjectName("edit_iteration")
        self.horizontalLayout_4.addWidget(self.edit_iteration)
        spacerItem = QtWidgets.QSpacerItem(135, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.checkbox_journal = QtWidgets.QCheckBox(self.frame_advanced)
        self.checkbox_journal.setObjectName("checkbox_journal")
        self.horizontalLayout_4.addWidget(self.checkbox_journal)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.Hlayout_journal = QtWidgets.QHBoxLayout()
        self.Hlayout_journal.setSpacing(10)
        self.Hlayout_journal.setObjectName("Hlayout_journal")
        self.label_journal_address = QtWidgets.QLabel(self.frame_advanced)
        self.label_journal_address.setMinimumSize(QtCore.QSize(70, 0))
        self.label_journal_address.setMaximumSize(QtCore.QSize(70, 28))
        self.label_journal_address.setObjectName("label_journal_address")
        self.Hlayout_journal.addWidget(self.label_journal_address)
        self.edit_journal_address = QtWidgets.QLineEdit(self.frame_advanced)
        self.edit_journal_address.setMinimumSize(QtCore.QSize(28, 0))
        self.edit_journal_address.setMaximumSize(QtCore.QSize(350, 28))
        self.edit_journal_address.setObjectName("edit_journal_address")
        self.Hlayout_journal.addWidget(self.edit_journal_address)
        self.btn_journal_address = QtWidgets.QToolButton(self.frame_advanced)
        self.btn_journal_address.setMinimumSize(QtCore.QSize(35, 30))
        self.btn_journal_address.setMaximumSize(QtCore.QSize(40, 30))
        self.btn_journal_address.setIcon(icon)
        self.btn_journal_address.setIconSize(QtCore.QSize(30, 30))
        self.btn_journal_address.setObjectName("btn_journal_address")
        self.Hlayout_journal.addWidget(self.btn_journal_address)
        self.verticalLayout_2.addLayout(self.Hlayout_journal)
        self.verticalLayout.addWidget(self.frame_advanced)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_extend = QtWidgets.QToolButton(Widget_add)
        self.btn_extend.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_extend.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../.designer/icon/extend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_extend.setIcon(icon1)
        self.btn_extend.setIconSize(QtCore.QSize(20, 20))
        self.btn_extend.setCheckable(True)
        self.btn_extend.setObjectName("btn_extend")
        self.horizontalLayout_2.addWidget(self.btn_extend)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_add = QtWidgets.QPushButton(Widget_add)
        self.btn_add.setMinimumSize(QtCore.QSize(100, 28))
        self.btn_add.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_2.addWidget(self.btn_add)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Widget_add)
        QtCore.QMetaObject.connectSlotsByName(Widget_add)

    def retranslateUi(self, Widget_add):
        _translate = QtCore.QCoreApplication.translate
        Widget_add.setWindowTitle(_translate("Widget_add", "选择新增项目"))
        self.label_project_address.setText(_translate("Widget_add", "项目文件"))
        self.btn_project_address.setText(_translate("Widget_add", "..."))
        self.label_iteration.setText(_translate("Widget_add", "计算步数"))
        self.checkbox_journal.setText(_translate("Widget_add", "使用journal"))
        self.label_journal_address.setText(_translate("Widget_add", "journal文件"))
        self.btn_journal_address.setText(_translate("Widget_add", "..."))
        self.btn_extend.setText(_translate("Widget_add", "..."))
        self.btn_add.setText(_translate("Widget_add", "确认增加"))
